# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: clinic-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: clinic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: clinic-app
    environment:
      DATABASE_URL: postgresql://postgres:admin123@postgres:5432/clinic_db?schema=public
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: 6p5SJP8HCQAzQ18GrjMBSfZG1Kub2lrgjav0PrIjmqo=
      SMSIR_API_KEY: ${SMSIR_API_KEY}
      SMSIR_LINE_NUMBER: ${SMSIR_LINE_NUMBER}
      ADMIN_PHONE: ${ADMIN_PHONE}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./public:/app/public
    restart: unless-stopped

volumes:
  postgres_data: